#!/bin/bash
#SBATCH --job-name=maxwell_filter
#SBATCH --ntasks-per-node=1
#SBATCH --mem=12G
#SBATCH --time=02:00:00

# PBS is a computer software that performs job-scheduling
# Copyright (c) 2020 brainlife.io at University of Texas at Austin and Indiana U
#
# This is the main file run by the brainlife.io orchestration system
#
# Author: Franco Pestilli


set -e
set -x

# Run the actual python code
singularity exec docker://brainlifemeeg/mne:1.12.1 python3 main.py
